# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.location_link import LocationLink

class TestLocationLink(unittest.TestCase):
    """LocationLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationLink:
        """Test LocationLink
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationLink`
        """
        model = LocationLink()
        if include_optional:
            return LocationLink(
                url = '',
                title = None,
                attributes = [
                    null
                    ],
                original_title = None,
                original_url = ''
            )
        else:
            return LocationLink(
        )
        """

    def testLocationLink(self):
        """Test LocationLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
