# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.class_schedules_api import ClassSchedulesApi


class TestClassSchedulesApi(unittest.TestCase):
    """ClassSchedulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClassSchedulesApi()

    def tearDown(self) -> None:
        pass

    def test_v3_class_schedules_term_code_course_id_get(self) -> None:
        """Test case for v3_class_schedules_term_code_course_id_get

        Get Class data for a scheduled Course by Course ID, in a specific Term
        """
        pass

    def test_v3_class_schedules_term_code_get(self) -> None:
        """Test case for v3_class_schedules_term_code_get

        Get the Course IDs that have one or more active and associated schedules in the given Term
        """
        pass

    def test_v3_class_schedules_term_code_subject_catalog_number_get(self) -> None:
        """Test case for v3_class_schedules_term_code_subject_catalog_number_get

        Get Class data for a scheduled Course by Subject and catalog number, in a specific Term
        """
        pass


if __name__ == '__main__':
    unittest.main()
