# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.site_opportunity import SiteOpportunity

class TestSiteOpportunity(unittest.TestCase):
    """SiteOpportunity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteOpportunity:
        """Test SiteOpportunity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteOpportunity`
        """
        model = SiteOpportunity()
        if include_optional:
            return SiteOpportunity(
                site_id = 56,
                unique_key = '',
                title = '',
                publisher_username = '',
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                opportunity_type = '',
                employment_type = '',
                rate_of_pay = '',
                rate_of_pay_type = '',
                content = '',
                posted_or_open_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                posted_or_open_date_time_zone = '',
                application_deadline_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                number_of_positions = '',
                application_uri = ''
            )
        else:
            return SiteOpportunity(
        )
        """

    def testSiteOpportunity(self):
        """Test SiteOpportunity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
