# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.food_services_franchise import FoodServicesFranchise

class TestFoodServicesFranchise(unittest.TestCase):
    """FoodServicesFranchise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoodServicesFranchise:
        """Test FoodServicesFranchise
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FoodServicesFranchise`
        """
        model = FoodServicesFranchise()
        if include_optional:
            return FoodServicesFranchise(
                id = 56,
                var_self = '',
                name = '',
                logo = openapi_client.models.logo.Logo(
                    id = '', 
                    url = '', 
                    filemime = '', 
                    filesize = '', 
                    width = '', 
                    height = '', 
                    alt = '', 
                    title = '', ),
                combos = [
                    openapi_client.models.combo.Combo(
                        name = '', 
                        image = openapi_client.models.combo_image.ComboImage(
                            id = '', 
                            url = '', 
                            filemime = '', 
                            filesize = '', 
                            width = '', 
                            height = '', 
                            alt = '', 
                            title = '', ), 
                        options = '', 
                        item = '', 
                        price = '', 
                        calories = null, )
                    ],
                individualitems = [
                    openapi_client.models.individual_item.IndividualItem(
                        name = '', 
                        photo = openapi_client.models.individual_item_photo.IndividualItemPhoto(
                            id = '', 
                            url = '', 
                            filemime = '', 
                            filesize = '', 
                            width = '', 
                            height = '', 
                            alt = '', 
                            title = '', ), 
                        price = '', 
                        calories = null, )
                    ],
                addons = [
                    openapi_client.models.addon.Addon(
                        name = '', 
                        photo = null, 
                        price = '', 
                        calories = null, )
                    ]
            )
        else:
            return FoodServicesFranchise(
        )
        """

    def testFoodServicesFranchise(self):
        """Test FoodServicesFranchise"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
