# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.en1 import En1

class TestEn1(unittest.TestCase):
    """En1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> En1:
        """Test En1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `En1`
        """
        model = En1()
        if include_optional:
            return En1(
                robots = openapi_client.models.robots.Robots(
                    value = openapi_client.models.value.Value(
                        index = 56, 
                        follow = 56, 
                        noindex = 56, 
                        nofollow = 56, 
                        noarchive = 56, 
                        nosnippet = 56, 
                        noodp = 56, 
                        noydir = 56, 
                        noimageindex = 56, 
                        notranslate = 56, ), )
            )
        else:
            return En1(
        )
        """

    def testEn1(self):
        """Test En1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
