# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.locpick import Locpick

class TestLocpick(unittest.TestCase):
    """Locpick unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Locpick:
        """Test Locpick
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Locpick`
        """
        model = Locpick()
        if include_optional:
            return Locpick(
                user_latitude = '',
                user_longitude = ''
            )
        else:
            return Locpick(
        )
        """

    def testLocpick(self):
        """Test Locpick"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
