# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.translations import Translations

class TestTranslations(unittest.TestCase):
    """Translations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Translations:
        """Test Translations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Translations`
        """
        model = Translations()
        if include_optional:
            return Translations(
                original = '',
                data = openapi_client.models.data.Data(
                    en = openapi_client.models.en2.En2(
                        entity_type = '', 
                        entity_id = '', 
                        revision_id = '', 
                        language = '', 
                        source = '', 
                        uid = '', 
                        status = '', 
                        translate = '', 
                        created = '', 
                        changed = '', ), )
            )
        else:
            return Translations(
        )
        """

    def testTranslations(self):
        """Test Translations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
