# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.wcms_api import WcmsApi


class TestWcmsApi(unittest.TestCase):
    """WcmsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WcmsApi()

    def tearDown(self) -> None:
        pass

    def test_v3_wcms_get(self) -> None:
        """Test case for v3_wcms_get

        Retrieves information about all active and published WCMS sites
        """
        pass

    def test_v3_wcms_id_events_get(self) -> None:
        """Test case for v3_wcms_id_events_get

        Retrieves all event items for a specific WCMS site by Site Id
        """
        pass

    def test_v3_wcms_id_get(self) -> None:
        """Test case for v3_wcms_id_get

        Retrieves information about a specific WCMS site by Site Id
        """
        pass

    def test_v3_wcms_id_news_get(self) -> None:
        """Test case for v3_wcms_id_news_get

        Retrieves all news items for a specific WCMS site by Site Id
        """
        pass

    def test_v3_wcms_id_opportunities_get(self) -> None:
        """Test case for v3_wcms_id_opportunities_get

        Retrieves all opportunity items for a specific WCMS site by Site Id
        """
        pass

    def test_v3_wcms_id_posts_get(self) -> None:
        """Test case for v3_wcms_id_posts_get

        Retrieves all blog post items for a specific WCMS site by Site Id
        """
        pass

    def test_v3_wcms_latestevents_max_items_get(self) -> None:
        """Test case for v3_wcms_latestevents_max_items_get

        Retrieves the latest events items across all WCMS sites, ordered by event start date
        """
        pass

    def test_v3_wcms_latestnews_max_items_get(self) -> None:
        """Test case for v3_wcms_latestnews_max_items_get

        Retrieves the latest news items across all WCMS sites, ordered by posted date
        """
        pass

    def test_v3_wcms_latestopportunities_max_items_get(self) -> None:
        """Test case for v3_wcms_latestopportunities_max_items_get

        Retrieves the latest opportunity items across all WCMS sites, ordered by posted/open date
        """
        pass

    def test_v3_wcms_latestposts_max_items_get(self) -> None:
        """Test case for v3_wcms_latestposts_max_items_get

        Retrieves the latest blog post items across all WCMS sites, ordered by posted date
        """
        pass


if __name__ == '__main__':
    unittest.main()
