# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.exam import Exam

class TestExam(unittest.TestCase):
    """Exam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Exam:
        """Test Exam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Exam`
        """
        model = Exam()
        if include_optional:
            return Exam(
                exam_display_name = '',
                sections = '',
                is_online_description = '',
                day = '',
                location = '',
                exam_window_start_date = '',
                exam_window_start_time = '',
                exam_duration = '',
                notes = '',
                term_code = ''
            )
        else:
            return Exam(
        )
        """

    def testExam(self):
        """Test Exam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
