# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subjects_api import SubjectsApi


class TestSubjectsApi(unittest.TestCase):
    """SubjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubjectsApi()

    def tearDown(self) -> None:
        pass

    def test_v3_subjects_associatedto_organization_code_get(self) -> None:
        """Test case for v3_subjects_associatedto_organization_code_get

        Gets Subject data for Subjects associated to an Academic Organization by Organization code
        """
        pass

    def test_v3_subjects_code_get(self) -> None:
        """Test case for v3_subjects_code_get

        Gets Subject data filtered by Subject code
        """
        pass

    def test_v3_subjects_get(self) -> None:
        """Test case for v3_subjects_get

        Gets all Subject data
        """
        pass


if __name__ == '__main__':
    unittest.main()
