# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.outlet_location import OutletLocation

class TestOutletLocation(unittest.TestCase):
    """OutletLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutletLocation:
        """Test OutletLocation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutletLocation`
        """
        model = OutletLocation()
        if include_optional:
            return OutletLocation(
                lid = '',
                name = '',
                street = '',
                additional = '',
                city = '',
                province = '',
                postal_code = '',
                country = '',
                latitude = '',
                longitude = '',
                source = '',
                is_primary = '',
                locpick = openapi_client.models.locpick.Locpick(
                    user_latitude = '', 
                    user_longitude = '', ),
                province_name = '',
                country_name = ''
            )
        else:
            return OutletLocation(
        )
        """

    def testOutletLocation(self):
        """Test OutletLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
