# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.academic_organization import AcademicOrganization

class TestAcademicOrganization(unittest.TestCase):
    """AcademicOrganization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AcademicOrganization:
        """Test AcademicOrganization
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AcademicOrganization`
        """
        model = AcademicOrganization()
        if include_optional:
            return AcademicOrganization(
                code = '',
                name = '',
                description = '',
                description_formal = '',
                associated_campus_code = ''
            )
        else:
            return AcademicOrganization(
        )
        """

    def testAcademicOrganization(self):
        """Test AcademicOrganization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
