# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.important_date import ImportantDate

class TestImportantDate(unittest.TestCase):
    """ImportantDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportantDate:
        """Test ImportantDate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportantDate`
        """
        model = ImportantDate()
        if include_optional:
            return ImportantDate(
                id = 56,
                name = '',
                description = '',
                important_date_type = '',
                details = [
                    openapi_client.models.important_date_details.ImportantDateDetails(
                        important_date_id = 56, 
                        term_id = 56, 
                        term_name = '', 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        notes = '', )
                    ],
                keywords = [
                    ''
                    ],
                audiences = [
                    ''
                    ]
            )
        else:
            return ImportantDate(
        )
        """

    def testImportantDate(self):
        """Test ImportantDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
