# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.exam_schedules_api import ExamSchedulesApi


class TestExamSchedulesApi(unittest.TestCase):
    """ExamSchedulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExamSchedulesApi()

    def tearDown(self) -> None:
        pass

    def test_v3_exam_schedules_code_get(self) -> None:
        """Test case for v3_exam_schedules_code_get

        Returns Exam Schedule data for the requested Term
        """
        pass

    def test_v3_exam_schedules_get(self) -> None:
        """Test case for v3_exam_schedules_get

        Returns Exam Schedule data for the current Term
        """
        pass


if __name__ == '__main__':
    unittest.main()
