# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.important_dates_api import ImportantDatesApi


class TestImportantDatesApi(unittest.TestCase):
    """ImportantDatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportantDatesApi()

    def tearDown(self) -> None:
        pass

    def test_v3_important_dates_get(self) -> None:
        """Test case for v3_important_dates_get

        Returns all current data for Important Dates
        """
        pass


if __name__ == '__main__':
    unittest.main()
