# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_v3_account_confirm_post(self) -> None:
        """Test case for v3_account_confirm_post

        Use this method to confirm your email and activate your account
        """
        pass

    def test_v3_account_email_api_key_reset_get(self) -> None:
        """Test case for v3_account_email_api_key_reset_get

        User this method to put your account in pending confirmation status and generate a new API key. Your old key will no longer grant access. The account will need to be confirmed again before the new key grants access.
        """
        pass

    def test_v3_account_email_get(self) -> None:
        """Test case for v3_account_email_get

        Use this method to see if an email has already been registered for an API key
        """
        pass

    def test_v3_account_email_notify_get(self) -> None:
        """Test case for v3_account_email_notify_get

        Use this method to have us re-send the confirmation email to an account pending confirmation, if it exists. The activation code will be reset in the process.
        """
        pass

    def test_v3_account_register_post(self) -> None:
        """Test case for v3_account_register_post

        Use this method to request an API key and begin your registration process
        """
        pass


if __name__ == '__main__':
    unittest.main()
