# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.holiday_dates_api import HolidayDatesApi


class TestHolidayDatesApi(unittest.TestCase):
    """HolidayDatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HolidayDatesApi()

    def tearDown(self) -> None:
        pass

    def test_v3_holiday_dates_paidholidays_get(self) -> None:
        """Test case for v3_holiday_dates_paidholidays_get

        Retrieves data for all paid holidays as published by Human Resources
        """
        pass

    def test_v3_holiday_dates_paidholidays_ics_get(self) -> None:
        """Test case for v3_holiday_dates_paidholidays_ics_get

        Retrieves data for all paid holidays as published by Human Resources, as an ICS format feed. Allows anonymous access.
        """
        pass

    def test_v3_holiday_dates_paidholidays_year_get(self) -> None:
        """Test case for v3_holiday_dates_paidholidays_year_get

        Retrieves data for paid holidays associated to the given year as published by Human Resources
        """
        pass


if __name__ == '__main__':
    unittest.main()
