# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.cuisine import Cuisine

class TestCuisine(unittest.TestCase):
    """Cuisine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cuisine:
        """Test Cuisine
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cuisine`
        """
        model = Cuisine()
        if include_optional:
            return Cuisine(
                id = '',
                var_self = '',
                name = '',
                description = ''
            )
        else:
            return Cuisine(
        )
        """

    def testCuisine(self):
        """Test Cuisine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
