# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.courses_api import CoursesApi


class TestCoursesApi(unittest.TestCase):
    """CoursesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoursesApi()

    def tearDown(self) -> None:
        pass

    def test_v3_courses_term_code_course_id_get(self) -> None:
        """Test case for v3_courses_term_code_course_id_get

        Get Course catalog data filtered by Term and Course ID, multiple Courses are usually cross listed
        """
        pass

    def test_v3_courses_term_code_course_id_offer_number_get(self) -> None:
        """Test case for v3_courses_term_code_course_id_offer_number_get

        Get Course catalog data filtered by Term, Course ID, and offer number
        """
        pass

    def test_v3_courses_term_code_get(self) -> None:
        """Test case for v3_courses_term_code_get

        Get all Course data for a Term
        """
        pass

    def test_v3_courses_term_code_subject_catalog_number_get(self) -> None:
        """Test case for v3_courses_term_code_subject_catalog_number_get

        Get Course catalog data filtered by Term, Subject, and catalog number
        """
        pass

    def test_v3_courses_term_code_subject_get(self) -> None:
        """Test case for v3_courses_term_code_subject_get

        Get Course catalog data filtered by Term and Subject code
        """
        pass


if __name__ == '__main__':
    unittest.main()
