# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.food_services_outlets_self import FoodServicesOutletsSelf

class TestFoodServicesOutletsSelf(unittest.TestCase):
    """FoodServicesOutletsSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoodServicesOutletsSelf:
        """Test FoodServicesOutletsSelf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FoodServicesOutletsSelf`
        """
        model = FoodServicesOutletsSelf()
        if include_optional:
            return FoodServicesOutletsSelf(
                title = '',
                href = ''
            )
        else:
            return FoodServicesOutletsSelf(
        )
        """

    def testFoodServicesOutletsSelf(self):
        """Test FoodServicesOutletsSelf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
