# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AcademicOrganization(BaseModel):
    """
    An Academic Organization at Waterloo is similar to a department
    """ # noqa: E501
    code: Optional[StrictStr] = Field(default=None, description="Unique Code of this Academic Organization")
    name: Optional[StrictStr] = Field(default=None, description="The Name for this Academic Organization, most often the display name")
    description: Optional[StrictStr] = Field(default=None, description="The short description for this Academic Organization")
    description_formal: Optional[StrictStr] = Field(default=None, description="The formal description for this Academic Organization, most often used in official capacity", alias="descriptionFormal")
    associated_campus_code: Optional[StrictStr] = Field(default=None, description="The Code for the Campus that this Academic Organization is assigned to", alias="associatedCampusCode")
    __properties: ClassVar[List[str]] = ["code", "name", "description", "descriptionFormal", "associatedCampusCode"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AcademicOrganization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if description_formal (nullable) is None
        # and model_fields_set contains the field
        if self.description_formal is None and "description_formal" in self.model_fields_set:
            _dict['descriptionFormal'] = None

        # set to None if associated_campus_code (nullable) is None
        # and model_fields_set contains the field
        if self.associated_campus_code is None and "associated_campus_code" in self.model_fields_set:
            _dict['associatedCampusCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AcademicOrganization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "descriptionFormal": obj.get("descriptionFormal"),
            "associatedCampusCode": obj.get("associatedCampusCode")
        })
        return _obj


