# coding: utf-8

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SiteEvent(BaseModel):
    """
    Model representing a WCMS Event item
    """ # noqa: E501
    site_id: Optional[StrictInt] = Field(default=None, description="Unique, numeric site ID", alias="siteId")
    unique_key: Optional[StrictStr] = Field(default=None, description="Unique Id of this evevnt item", alias="uniqueKey")
    title: Optional[StrictStr] = Field(default=None, description="Title of the event")
    event_start_date: Optional[datetime] = Field(default=None, description="Start date of the event", alias="eventStartDate")
    event_end_date: Optional[datetime] = Field(default=None, description="End date of the event", alias="eventEndDate")
    recur_rule: Optional[StrictStr] = Field(default=None, description="Description of the event recurrence rule", alias="recurRule")
    event_timezone: Optional[StrictStr] = Field(default=None, description="Time zone description of the event dates", alias="eventTimezone")
    item_uri: Optional[StrictStr] = Field(default=None, description="Link to the Event", alias="itemUri")
    event_tags: Optional[StrictStr] = Field(default=None, description="Tag(s) representing the event", alias="eventTags")
    event_type: Optional[StrictStr] = Field(default=None, description="Type of the event", alias="eventType")
    event_website: Optional[StrictStr] = Field(default=None, description="Supplemental URI for the event", alias="eventWebsite")
    audience: Optional[StrictStr] = Field(default=None, description="Tag(s) representing the intended audience for the event")
    cost: Optional[StrictStr] = Field(default=None, description="Cost of the event")
    host: Optional[StrictStr] = Field(default=None, description="Event host information")
    location_id: Optional[StrictInt] = Field(default=None, description="Unique Id of the location hosting the event", alias="locationId")
    location_name: Optional[StrictStr] = Field(default=None, description="Display name of the location hosting the event", alias="locationName")
    updated_date: Optional[datetime] = Field(default=None, description="Date item last updated", alias="updatedDate")
    content: Optional[StrictStr] = Field(default=None, description="Description content for the event, often includes HTML markup")
    __properties: ClassVar[List[str]] = ["siteId", "uniqueKey", "title", "eventStartDate", "eventEndDate", "recurRule", "eventTimezone", "itemUri", "eventTags", "eventType", "eventWebsite", "audience", "cost", "host", "locationId", "locationName", "updatedDate", "content"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SiteEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if unique_key (nullable) is None
        # and model_fields_set contains the field
        if self.unique_key is None and "unique_key" in self.model_fields_set:
            _dict['uniqueKey'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if event_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.event_start_date is None and "event_start_date" in self.model_fields_set:
            _dict['eventStartDate'] = None

        # set to None if event_end_date (nullable) is None
        # and model_fields_set contains the field
        if self.event_end_date is None and "event_end_date" in self.model_fields_set:
            _dict['eventEndDate'] = None

        # set to None if recur_rule (nullable) is None
        # and model_fields_set contains the field
        if self.recur_rule is None and "recur_rule" in self.model_fields_set:
            _dict['recurRule'] = None

        # set to None if event_timezone (nullable) is None
        # and model_fields_set contains the field
        if self.event_timezone is None and "event_timezone" in self.model_fields_set:
            _dict['eventTimezone'] = None

        # set to None if item_uri (nullable) is None
        # and model_fields_set contains the field
        if self.item_uri is None and "item_uri" in self.model_fields_set:
            _dict['itemUri'] = None

        # set to None if event_tags (nullable) is None
        # and model_fields_set contains the field
        if self.event_tags is None and "event_tags" in self.model_fields_set:
            _dict['eventTags'] = None

        # set to None if event_type (nullable) is None
        # and model_fields_set contains the field
        if self.event_type is None and "event_type" in self.model_fields_set:
            _dict['eventType'] = None

        # set to None if event_website (nullable) is None
        # and model_fields_set contains the field
        if self.event_website is None and "event_website" in self.model_fields_set:
            _dict['eventWebsite'] = None

        # set to None if audience (nullable) is None
        # and model_fields_set contains the field
        if self.audience is None and "audience" in self.model_fields_set:
            _dict['audience'] = None

        # set to None if cost (nullable) is None
        # and model_fields_set contains the field
        if self.cost is None and "cost" in self.model_fields_set:
            _dict['cost'] = None

        # set to None if host (nullable) is None
        # and model_fields_set contains the field
        if self.host is None and "host" in self.model_fields_set:
            _dict['host'] = None

        # set to None if location_id (nullable) is None
        # and model_fields_set contains the field
        if self.location_id is None and "location_id" in self.model_fields_set:
            _dict['locationId'] = None

        # set to None if location_name (nullable) is None
        # and model_fields_set contains the field
        if self.location_name is None and "location_name" in self.model_fields_set:
            _dict['locationName'] = None

        # set to None if updated_date (nullable) is None
        # and model_fields_set contains the field
        if self.updated_date is None and "updated_date" in self.model_fields_set:
            _dict['updatedDate'] = None

        # set to None if content (nullable) is None
        # and model_fields_set contains the field
        if self.content is None and "content" in self.model_fields_set:
            _dict['content'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SiteEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "siteId": obj.get("siteId"),
            "uniqueKey": obj.get("uniqueKey"),
            "title": obj.get("title"),
            "eventStartDate": obj.get("eventStartDate"),
            "eventEndDate": obj.get("eventEndDate"),
            "recurRule": obj.get("recurRule"),
            "eventTimezone": obj.get("eventTimezone"),
            "itemUri": obj.get("itemUri"),
            "eventTags": obj.get("eventTags"),
            "eventType": obj.get("eventType"),
            "eventWebsite": obj.get("eventWebsite"),
            "audience": obj.get("audience"),
            "cost": obj.get("cost"),
            "host": obj.get("host"),
            "locationId": obj.get("locationId"),
            "locationName": obj.get("locationName"),
            "updatedDate": obj.get("updatedDate"),
            "content": obj.get("content")
        })
        return _obj


