# coding: utf-8

# flake8: noqa

"""
    Waterloo OpenData API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.academic_organizations_api import AcademicOrganizationsApi
from openapi_client.api.account_api import AccountApi
from openapi_client.api.class_schedules_api import ClassSchedulesApi
from openapi_client.api.courses_api import CoursesApi
from openapi_client.api.exam_schedules_api import ExamSchedulesApi
from openapi_client.api.food_services_api import FoodServicesApi
from openapi_client.api.holiday_dates_api import HolidayDatesApi
from openapi_client.api.important_dates_api import ImportantDatesApi
from openapi_client.api.locations_api import LocationsApi
from openapi_client.api.subjects_api import SubjectsApi
from openapi_client.api.terms_api import TermsApi
from openapi_client.api.wcms_api import WcmsApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.academic_organization import AcademicOrganization
from openapi_client.models.addon import Addon
from openapi_client.models.body import Body
from openapi_client.models.changed import Changed
from openapi_client.models.class_instructor import ClassInstructor
from openapi_client.models.class_schedule import ClassSchedule
from openapi_client.models.closed import Closed
from openapi_client.models.combo import Combo
from openapi_client.models.combo_image import ComboImage
from openapi_client.models.comment_count import CommentCount
from openapi_client.models.course import Course
from openapi_client.models.created import Created
from openapi_client.models.cuisine import Cuisine
from openapi_client.models.current import Current
from openapi_client.models.data import Data
from openapi_client.models.en import En
from openapi_client.models.en1 import En1
from openapi_client.models.en2 import En2
from openapi_client.models.exam import Exam
from openapi_client.models.feature import Feature
from openapi_client.models.field_combos import FieldCombos
from openapi_client.models.field_franchise_logo import FieldFranchiseLogo
from openapi_client.models.food_services_franchise import FoodServicesFranchise
from openapi_client.models.food_services_franchises import FoodServicesFranchises
from openapi_client.models.food_services_franchises_self import FoodServicesFranchisesSelf
from openapi_client.models.food_services_outlet import FoodServicesOutlet
from openapi_client.models.food_services_outlet_image import FoodServicesOutletImage
from openapi_client.models.food_services_outlet_photo import FoodServicesOutletPhoto
from openapi_client.models.food_services_outlets import FoodServicesOutlets
from openapi_client.models.food_services_outlets_self import FoodServicesOutletsSelf
from openapi_client.models.franchise_menu import FranchiseMenu
from openapi_client.models.geometry import Geometry
from openapi_client.models.hours_change import HoursChange
from openapi_client.models.important_date import ImportantDate
from openapi_client.models.important_date_details import ImportantDateDetails
from openapi_client.models.individual_item import IndividualItem
from openapi_client.models.individual_item_photo import IndividualItemPhoto
from openapi_client.models.last_activity import LastActivity
from openapi_client.models.location import Location
from openapi_client.models.location_geo import LocationGeo
from openapi_client.models.location_link import LocationLink
from openapi_client.models.locpick import Locpick
from openapi_client.models.logo import Logo
from openapi_client.models.metatags import Metatags
from openapi_client.models.model_class import ModelClass
from openapi_client.models.my_revision import MyRevision
from openapi_client.models.name import Name
from openapi_client.models.opening_hour import OpeningHour
from openapi_client.models.outlet_location import OutletLocation
from openapi_client.models.outlet_type import OutletType
from openapi_client.models.paid_holiday import PaidHoliday
from openapi_client.models.path import Path
from openapi_client.models.payment_accepted import PaymentAccepted
from openapi_client.models.published import Published
from openapi_client.models.rdf_mapping import RdfMapping
from openapi_client.models.robots import Robots
from openapi_client.models.site import Site
from openapi_client.models.site_blog_post import SiteBlogPost
from openapi_client.models.site_event import SiteEvent
from openapi_client.models.site_news import SiteNews
from openapi_client.models.site_opportunity import SiteOpportunity
from openapi_client.models.subject import Subject
from openapi_client.models.term import Term
from openapi_client.models.title import Title
from openapi_client.models.title_field import TitleField
from openapi_client.models.translations import Translations
from openapi_client.models.uid import Uid
from openapi_client.models.und import Und
from openapi_client.models.und1 import Und1
from openapi_client.models.value import Value
from openapi_client.models.workbench_moderation import WorkbenchModeration
